# ======================
# TEST DATABASE (TESTCONTAINERS)
# ======================

spring.datasource.url=jdbc:tc:postgresql:16-alpine:///testdb
spring.datasource.driver-class-name=org.testcontainers.jdbc.ContainerDatabaseDriver
spring.datasource.hikari.registerMBeans=true
# ======================
# JPA
# ======================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false

spring.test.database.replace=none
