spring.application.name=token-api-java

server.port=${PORT:5001}
spring.security.user.name=${SPRING_SECURITY_USER:admin}
spring.security.user.password=${SPRING_SECURITY_PASSWORD:admin}

# ======================
# JPA
# ======================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# ======================
# SQL INIT
# ======================
spring.sql.init.mode=never
spring.sql.init.schema-locations=classpath:schemas/*.sql

# ======================
# SWAGGER
# ======================
springdoc.swagger-ui.tagsSorter=alpha