INSERT INTO APPLICATIONS(ID, APP_NAME, API_KEY, MAX_TOKEN_AMOUNT, MIN_TOKEN_AMOUNT, REGENDAYS, REGENHOURS, REGENMINS) VALUES (1L, 'testApp', 'xxa', 15L, 0L, 1, 12, 0);
INSERT INTO APPLICATIONS(ID, APP_NAME, API_KEY, MAX_TOKEN_AMOUNT, MIN_TOKEN_AMOUNT, REGENDAYS, REGENHOURS, REGENMINS) VALUES (2L, 'testApp2', 'xxb', 300L, 0L, 1, 22, 0);
